# Simplified golangci-lint configuration
run:
  timeout: 5m
  tests: true
linters-settings:
  godot:
    # Completely disable checking for periods at the end of comments
    exclude: [".*"]
  goimports:
    local-prefixes: github.com/nhn/oss/oss-models
# Core linters that provide the most value
linters:
  disable-all: true
  enable:
    - errcheck # Checks for unchecked errors
    - govet # Reports suspicious constructs
    - staticcheck # Go static analysis
    - stylecheck # Stylecheck replaces golint
    - goimports # Formats imports and code
    - gofmt # Checks if code was gofmt-ed
    - ineffassign # Detects unused assignments
    - misspell # Finds commonly misspelled English words
    - unused # Checks for unused code
    - godot # Check if comments end in a period
issues:
  exclude-files:
    - "zz_generated.deepcopy.go"
  exclude-dirs:
    - bin
    - crds
  exclude-rules:
    # Exclude test files from certain linters
    - path: _test\.go
      linters:
        - errcheck
    # Exclude auto-generated files
    - path: zz_generated\..*\.go
      linters:
        - staticcheck
        - stylecheck
        - goimports
        - unused
    # Exclude init functions
    - path: pkg/v1alpha1/(vitistack|kubernetes_provider|machine_provider)\.go
      text: "don't use `init` function"
      linters:
        - gochecknoinits
    # Combined rule for kubebuilder comments
    - linters:
        - godot
        - stylecheck
      source: "^// \\+.*$"
  max-same-issues: 5
  max-issues-per-linter: 50