---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
      url: https://host.docker.internal:9443/mutate--v1-service
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0VENDQXAyZ0F3SUJBZ0lVUUdkM2VkdmJsc1dycEtqenFYbXJBREU1Z0lrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1ZERUxNQWtHQTFVRUJoTUNUazh4RWpBUUJnTlZCQWdNQ1ZSU1QwNUVSVXhCUnpFU01CQUdBMVVFQnd3SgpWSEp2Ym1Sb1pXbHRNUjB3R3dZRFZRUUREQlJvYjNOMExtUnZZMnRsY2k1cGJuUmxjbTVoYkRBZUZ3MHlOakF6Ck1USXhNalV4TUROYUZ3MHlOekF6TVRJeE1qVXhNRE5hTUZReEN6QUpCZ05WQkFZVEFrNVBNUkl3RUFZRFZRUUkKREFsVVVrOU9SRVZNUVVjeEVqQVFCZ05WQkFjTUNWUnliMjVrYUdWcGJURWRNQnNHQTFVRUF3d1VhRzl6ZEM1awpiMk5yWlhJdWFXNTBaWEp1WVd3d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNlCjRwa1ZlNlUwdmVVVUVqUVFscS9ab09QbE9qaG50U01uMHM3b1Q5b1Z3dnBPNWxyWDRQR1E2KytZbmFkelpwYVQKU2JwK3pJd1FJWHpjWmJ5TTNIVmI2N3dibFArdmVnR0tFVTNBRnhhWVE3Q1ZWdWJKSkVDRE9uNHZsT1NWNk1YcQpqLzUwN2ZOckZ2Z3ZhaE4vK283SDdpVjFSZjFWbE9VdzZ3SnljMWdzWE5BektaY2FRL0ZHcE5Ca1haWWNpZFRUCittWlBXTE5yMGQ3M00wUTdWaTZreXc0bk9PS1JjNWVOMXAvNE0rTGE1N04vR28wTE1UTCtPTVJoZGlhTm1zUloKZzF3L2JsRVNqMnljVndLTEhLSnp0MUlOMW0yZFNOUHg1YTBQbytMMlhzeFJGOHpNSWRNNVdnYmZHYml4Z2cyRAovb2dTV2txSFlDVnlGbm1Sc0JhUEFnTUJBQUdqZnpCOU1CMEdBMVVkRGdRV0JCU3g4dzJwTDdnQjJrL2c5ZGpsCmtvUE5BNmlPM0RBZkJnTlZIU01FR0RBV2dCU3g4dzJwTDdnQjJrL2c5ZGpsa29QTkE2aU8zREFQQmdOVkhSTUIKQWY4RUJUQURBUUgvTUNvR0ExVWRFUVFqTUNHQ0NXeHZZMkZzYUc5emRJSVVhRzl6ZEM1a2IyTnJaWEl1YVc1MApaWEp1WVd3d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEeEorM00rZDJzNVZIUjJJZElOMDFsZ3FTemppc2ZkClVVS1ZLMEZ3VUNMVkJ5TXlrdExTTHZGcXNMNEpLUUZkcysycDh0dFdWQW43ckUrQmFPNkM0OEVIOC9RS0p6RTQKOGN4RFpCS2ZuVGhJcEtJekpOS213RElXYzNHOW1BZWRwQi9JK215S040NUdVL3h0UXk5VnlVdXkxTGlURGRQSQpHVlAxOVphNU5aellSNGxnWklBWkkvV3lXbmFCcTkrL3B4ZkN6V1hmU3RlQ1cxR1NxSkFxbmZ3YWExSmN3ajArCnlYcUF1WU52bGswUXlqa2wvbEg0M1dyWmZ5L0dwRndDek1pMkhmRXVjVkE4a05CdEN0aE5JdXl5eUE5SHhiNHAKM1E1K2JpNlZLVVpVTVNhd2tEd3VMczJRR1p1VFpVRCtpcHpkWWlBS2ltWG1XUFBiNHBVb0lsdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  failurePolicy: Fail
  name: host.docker.internal
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  sideEffects: NoneOnDryRun
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - cert-manager
          - kube-node-lease
          - kube-public
          - kube-system
          - kubemacpool-system
          - kubelet-serving-cert-approver
          - kubevirt
          - eventus
          - fluent
          - kyverno
          - metallb-system
          - monitoring
          - rook-ceph
          - falco
          - trivy-system
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  name: host.docker.internal
  clientConfig:
      url: https://host.docker.internal:9443/validate--v1-service
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0VENDQXAyZ0F3SUJBZ0lVUUdkM2VkdmJsc1dycEtqenFYbXJBREU1Z0lrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1ZERUxNQWtHQTFVRUJoTUNUazh4RWpBUUJnTlZCQWdNQ1ZSU1QwNUVSVXhCUnpFU01CQUdBMVVFQnd3SgpWSEp2Ym1Sb1pXbHRNUjB3R3dZRFZRUUREQlJvYjNOMExtUnZZMnRsY2k1cGJuUmxjbTVoYkRBZUZ3MHlOakF6Ck1USXhNalV4TUROYUZ3MHlOekF6TVRJeE1qVXhNRE5hTUZReEN6QUpCZ05WQkFZVEFrNVBNUkl3RUFZRFZRUUkKREFsVVVrOU9SRVZNUVVjeEVqQVFCZ05WQkFjTUNWUnliMjVrYUdWcGJURWRNQnNHQTFVRUF3d1VhRzl6ZEM1awpiMk5yWlhJdWFXNTBaWEp1WVd3d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNlCjRwa1ZlNlUwdmVVVUVqUVFscS9ab09QbE9qaG50U01uMHM3b1Q5b1Z3dnBPNWxyWDRQR1E2KytZbmFkelpwYVQKU2JwK3pJd1FJWHpjWmJ5TTNIVmI2N3dibFArdmVnR0tFVTNBRnhhWVE3Q1ZWdWJKSkVDRE9uNHZsT1NWNk1YcQpqLzUwN2ZOckZ2Z3ZhaE4vK283SDdpVjFSZjFWbE9VdzZ3SnljMWdzWE5BektaY2FRL0ZHcE5Ca1haWWNpZFRUCittWlBXTE5yMGQ3M00wUTdWaTZreXc0bk9PS1JjNWVOMXAvNE0rTGE1N04vR28wTE1UTCtPTVJoZGlhTm1zUloKZzF3L2JsRVNqMnljVndLTEhLSnp0MUlOMW0yZFNOUHg1YTBQbytMMlhzeFJGOHpNSWRNNVdnYmZHYml4Z2cyRAovb2dTV2txSFlDVnlGbm1Sc0JhUEFnTUJBQUdqZnpCOU1CMEdBMVVkRGdRV0JCU3g4dzJwTDdnQjJrL2c5ZGpsCmtvUE5BNmlPM0RBZkJnTlZIU01FR0RBV2dCU3g4dzJwTDdnQjJrL2c5ZGpsa29QTkE2aU8zREFQQmdOVkhSTUIKQWY4RUJUQURBUUgvTUNvR0ExVWRFUVFqTUNHQ0NXeHZZMkZzYUc5emRJSVVhRzl6ZEM1a2IyTnJaWEl1YVc1MApaWEp1WVd3d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEeEorM00rZDJzNVZIUjJJZElOMDFsZ3FTemppc2ZkClVVS1ZLMEZ3VUNMVkJ5TXlrdExTTHZGcXNMNEpLUUZkcysycDh0dFdWQW43ckUrQmFPNkM0OEVIOC9RS0p6RTQKOGN4RFpCS2ZuVGhJcEtJekpOS213RElXYzNHOW1BZWRwQi9JK215S040NUdVL3h0UXk5VnlVdXkxTGlURGRQSQpHVlAxOVphNU5aellSNGxnWklBWkkvV3lXbmFCcTkrL3B4ZkN6V1hmU3RlQ1cxR1NxSkFxbmZ3YWExSmN3ajArCnlYcUF1WU52bGswUXlqa2wvbEg0M1dyWmZ5L0dwRndDek1pMkhmRXVjVkE4a05CdEN0aE5JdXl5eUE5SHhiNHAKM1E1K2JpNlZLVVpVTVNhd2tEd3VMczJRR1p1VFpVRCtpcHpkWWlBS2ltWG1XUFBiNHBVb0lsdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  failurePolicy: Fail
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - services
  sideEffects: None
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - cert-manager
          - kube-node-lease
          - kube-public
          - kube-system
          - kubemacpool-system
          - kubelet-serving-cert-approver
          - kubevirt
          - eventus
          - fluent
          - kyverno
          - metallb-system
          - monitoring
          - rook-ceph
          - falco
          - trivy-system          
