---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
      url: https://host.docker.internal:9443/mutate--v1-service
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0VENDQXAyZ0F3SUJBZ0lVWEVPRkxzbTEwL2RCWlk2eTRBTG9iWkVDMWlJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1ZERUxNQWtHQTFVRUJoTUNUazh4RWpBUUJnTlZCQWdNQ1ZSU1QwNUVSVXhCUnpFU01CQUdBMVVFQnd3SgpWSEp2Ym1Sb1pXbHRNUjB3R3dZRFZRUUREQlJvYjNOMExtUnZZMnRsY2k1cGJuUmxjbTVoYkRBZUZ3MHlOVEV3Ck1UVXhOekEyTXpSYUZ3MHlOakV3TVRVeE56QTJNelJhTUZReEN6QUpCZ05WQkFZVEFrNVBNUkl3RUFZRFZRUUkKREFsVVVrOU9SRVZNUVVjeEVqQVFCZ05WQkFjTUNWUnliMjVrYUdWcGJURWRNQnNHQTFVRUF3d1VhRzl6ZEM1awpiMk5yWlhJdWFXNTBaWEp1WVd3d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURBCngxYUtRT2Y2T092VXlua0J6eUFiNldKNGNFUXFGVkJPTWtQNzlOZTlzNlMyOURSa1I0Z3JHTG5SM2ZZZ3Y3azEKREhwblpPU2VpZkNUcGZUdTltY2RwSFVTcVVFVnIwRVpTR2tTVjNoZXBQRGRxRkJPK1liKzc3VmZYVmhVZlFQVAp6b3RzMDhSci9zdmgxK2tkMWhMUWlSdW8wdGhvd0FrU1o1d3V4a1o5SnZmMzM0Q2UxamtYandZakVkaXN3VkEzCmkrOEV0UzJrbFVPMVN5cm1MQ3EzNUFtWCt4VnBsN3FqeVV3bEhvS1FoVXo0QzdKQ1hTWnZ4ZkNhdjJUWEEyN2EKb0RrMzhNSlowUVV4Zk53bkZmVGJiRmdCa1ZzYyszNWtsd2d6UkRVSnBPbWgxQkVhZjBZMGFZT0Y3bEVkeHRscQp5Vi9xam0xa0szZzdEdk1EcVE5WEFnTUJBQUdqZnpCOU1CMEdBMVVkRGdRV0JCUVo5bG15Mmx3NG1XbGxQUndzCnNBMFIzb0FaK3pBZkJnTlZIU01FR0RBV2dCUVo5bG15Mmx3NG1XbGxQUndzc0EwUjNvQVorekFQQmdOVkhSTUIKQWY4RUJUQURBUUgvTUNvR0ExVWRFUVFqTUNHQ0NXeHZZMkZzYUc5emRJSVVhRzl6ZEM1a2IyTnJaWEl1YVc1MApaWEp1WVd3d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBY3FzOWhZSm04ZWNGeTJFczdudXVtd0x2OEFCUFBICmZoQ1d1SXh5NFcxSkxMZUpWc3RTYUttbHBWYmo0SWc0SG1pb1haOEFBZFJBb1h5dUJmUDVDRDJLTENzUDM2cHUKWkpwdXVqREhWL1V2TmY5aW5HajZaREMydENtbmxhbmlwOVN5Wk9qRitSOHRBME5sVEY2cm4vSm9TdW4rSysrWQpQNGJOMWZkd0tvSjZ2MkJSUld4UjYzQnRkdFpYVnFzZklZT2dFeGJ2ZkV1NEtua0RvNDUyc2xiSTVhVmxRVHhlClpxVHkyMk01V0JMQ0I0QUJPL0JQck9pMUNMYnBIQkkrNGlwalpCRXlKY1p1OHNJSDE2aUlvNG8ya3kyQjdKOEwKdG5jU3dLL2VaYjY5SGVlMW8vd24rSXFXYnU1RmtTSXUvRGF1aGlBTEg4L2RTOW10cjhwY21NOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  failurePolicy: Fail
  name: host.docker.internal
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  sideEffects: NoneOnDryRun
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - cert-manager
          - kube-node-lease
          - kube-public
          - kube-system
          - kubemacpool-system
          - kubelet-serving-cert-approver
          - kubevirt
          - eventus
          - fluent
          - kyverno
          - metallb-system
          - monitoring
          - rook-ceph
          - falco
          - trivy-system
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  name: host.docker.internal
  clientConfig:
      url: https://host.docker.internal:9443/validate--v1-service
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0VENDQXAyZ0F3SUJBZ0lVWEVPRkxzbTEwL2RCWlk2eTRBTG9iWkVDMWlJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1ZERUxNQWtHQTFVRUJoTUNUazh4RWpBUUJnTlZCQWdNQ1ZSU1QwNUVSVXhCUnpFU01CQUdBMVVFQnd3SgpWSEp2Ym1Sb1pXbHRNUjB3R3dZRFZRUUREQlJvYjNOMExtUnZZMnRsY2k1cGJuUmxjbTVoYkRBZUZ3MHlOVEV3Ck1UVXhOekEyTXpSYUZ3MHlOakV3TVRVeE56QTJNelJhTUZReEN6QUpCZ05WQkFZVEFrNVBNUkl3RUFZRFZRUUkKREFsVVVrOU9SRVZNUVVjeEVqQVFCZ05WQkFjTUNWUnliMjVrYUdWcGJURWRNQnNHQTFVRUF3d1VhRzl6ZEM1awpiMk5yWlhJdWFXNTBaWEp1WVd3d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURBCngxYUtRT2Y2T092VXlua0J6eUFiNldKNGNFUXFGVkJPTWtQNzlOZTlzNlMyOURSa1I0Z3JHTG5SM2ZZZ3Y3azEKREhwblpPU2VpZkNUcGZUdTltY2RwSFVTcVVFVnIwRVpTR2tTVjNoZXBQRGRxRkJPK1liKzc3VmZYVmhVZlFQVAp6b3RzMDhSci9zdmgxK2tkMWhMUWlSdW8wdGhvd0FrU1o1d3V4a1o5SnZmMzM0Q2UxamtYandZakVkaXN3VkEzCmkrOEV0UzJrbFVPMVN5cm1MQ3EzNUFtWCt4VnBsN3FqeVV3bEhvS1FoVXo0QzdKQ1hTWnZ4ZkNhdjJUWEEyN2EKb0RrMzhNSlowUVV4Zk53bkZmVGJiRmdCa1ZzYyszNWtsd2d6UkRVSnBPbWgxQkVhZjBZMGFZT0Y3bEVkeHRscQp5Vi9xam0xa0szZzdEdk1EcVE5WEFnTUJBQUdqZnpCOU1CMEdBMVVkRGdRV0JCUVo5bG15Mmx3NG1XbGxQUndzCnNBMFIzb0FaK3pBZkJnTlZIU01FR0RBV2dCUVo5bG15Mmx3NG1XbGxQUndzc0EwUjNvQVorekFQQmdOVkhSTUIKQWY4RUJUQURBUUgvTUNvR0ExVWRFUVFqTUNHQ0NXeHZZMkZzYUc5emRJSVVhRzl6ZEM1a2IyTnJaWEl1YVc1MApaWEp1WVd3d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBY3FzOWhZSm04ZWNGeTJFczdudXVtd0x2OEFCUFBICmZoQ1d1SXh5NFcxSkxMZUpWc3RTYUttbHBWYmo0SWc0SG1pb1haOEFBZFJBb1h5dUJmUDVDRDJLTENzUDM2cHUKWkpwdXVqREhWL1V2TmY5aW5HajZaREMydENtbmxhbmlwOVN5Wk9qRitSOHRBME5sVEY2cm4vSm9TdW4rSysrWQpQNGJOMWZkd0tvSjZ2MkJSUld4UjYzQnRkdFpYVnFzZklZT2dFeGJ2ZkV1NEtua0RvNDUyc2xiSTVhVmxRVHhlClpxVHkyMk01V0JMQ0I0QUJPL0JQck9pMUNMYnBIQkkrNGlwalpCRXlKY1p1OHNJSDE2aUlvNG8ya3kyQjdKOEwKdG5jU3dLL2VaYjY5SGVlMW8vd24rSXFXYnU1RmtTSXUvRGF1aGlBTEg4L2RTOW10cjhwY21NOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  failurePolicy: Fail
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - services
  sideEffects: None
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - cert-manager
          - kube-node-lease
          - kube-public
          - kube-system
          - kubemacpool-system
          - kubelet-serving-cert-approver
          - kubevirt
          - eventus
          - fluent
          - kyverno
          - metallb-system
          - monitoring
          - rook-ceph
          - falco
          - trivy-system          
