apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ipam
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
- apiGroups: ["*"]
  resources: ["secrets","services"]
  verbs: ["get", "list", "watch","create","update"]
- apiGroups: ["*"]
  resources: ["namespaces","pods"]
  verbs: ["get", "list","watch"]
- apiGroups: ["metallb.io"]
  resources: ["ipaddresspools"]
  verbs: ["get", "list", "watch", "create","update"]
