---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: ipam-system/ipam-serving-cert
  name: ipam-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: ipam-webhook-service
      namespace: ipam-system
      path: /mutate--v1-service
  failurePolicy: Fail
  name: mservice-v1.kb.io
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - cert-manager
      - kube-node-lease
      - kube-public
      - kube-system
      - kubemacpool-system
      - kubelet-serving-cert-approver
      - kubevirt
      - letsencrypt
      - eventus
      - fluent
      - kyverno
      - metallb-system
      - monitoring
      - rook-ceph
      - falco
      - trivy-system
      - prometheus-operator
      - prometheus-blackbox-exporter
      - ipam-system
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  sideEffects: NoneOnDryRun
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: ipam-system/ipam-serving-cert
  name: ipam-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: ipam-webhook-service
      namespace: ipam-system
      path: /validate--v1-service
  failurePolicy: Fail
  name: vservice-v1.kb.io
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - cert-manager
      - kube-node-lease
      - kube-public
      - kube-system
      - kubemacpool-system
      - kubelet-serving-cert-approver
      - kubevirt
      - letsencrypt
      - eventus
      - fluent
      - kyverno
      - metallb-system
      - monitoring
      - rook-ceph
      - falco
      - prometheus-operator
      - prometheus-blackbox-exporter
      - trivy-system
      - ipam-system
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - services
  sideEffects: None
